[managers.system]
items = [
    "hyprland",
    "hyprpaper",
    "hyprpicker",
    "hypridle",
    "hyprlock",
    "hyprcursor",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal-gtk",
    "polkit"
]