[managers.system]
items = [
    "wofi",
    "xorg-wayland",
    "xorg-xlsclients",
    "qt5-wayland",
    "glfw-wayland",
    "xdg-desktop-portal-wlr",
    "grim",
    "grimshot",
    "wl-clipboard"
]
