group {
    groupbar {
        col.active = rgba(496156ee)
        col.inactive = rgba(7a8478aa)
    }

    col.border_active = rgba(7fbbb3ee) rgba(83c092ee) 45deg
    col.border_inactive = rgba(7a8478aa)
}