group {
    groupbar {
        col.active = rgba(272E33ff)
        col.inactive = rgba(272E33ff)
        font_size = 10
        gradients = false
        indicator_height = 16
        indicator_gap = -3
        height = 1
        round_only_edges = true
        text_offset = -6
        text_color = rgb(ffffff)
        gaps_in = 0
        gaps_out = 0
    }

    col.border_active = rgba(a0a0a0ee)
    col.border_inactive = rgba(7d7d7daa)
}