monitor = DP-1, 2560x1440@171, 1920x0, auto
monitor = HDMI-A-1, 1920x1080@60, 0x0, auto
# monitor = HDMI-A-2, disable
# monitor = HDMI-A-2, 3840x2160@60, 4480x0, 2
monitor = , preferred, auto, auto

source = ~/.config/hypr/modules/tv.conf