#!/bin/bash

entries="TV On\nTv Gaming\nTv Off"

selected=$($HOME/.config/wofi-monitor.sh 250 100 "$entries")

case $selected in
  on)
    state="3840x2160@60"
    ;;
  gaming)
    state="3840x2160@120"
    ;;
  off)
    state="disabled"
    ;;
  *)
    exit 0
    ;; 
esac

file=$(cat << EOM
# auto generated by monitor-selector.sh. Do not modify!!!
monitor = HDMI-A-2, $state, 4480x0, 2
EOM
)

echo "$file" > ~/.config/hypr/modules/tv.conf

