[managers.system]
items = [
    "flatpak",
    "visual-studio-code-bin",
    "vesktop",
    "alacritty",
    "spotify-launcher",
    "awf-gtk3",
    "nemo",
    "fontpreview",
    "sxiv",
    "mako",
    "wine",
    "tidal-hifi-git",
    "vice",
    "auto-cpufreq",
    "envycontrol"
]

[managers.serv_now]
items = [
    "auto-cpufreq"
]
